env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
  import/no-extraneous-dependencies: 0
  quotes: 0
